# Generated by Django 4.1.6 on 2023-02-12 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quoteapp", "0003_tag_quote_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quote",
            old_name="qoute",
            new_name="quote",
        ),
    ]
