# Generated by Django 4.1.6 on 2023-02-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quoteapp", "0005_alter_author_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="quote",
            field=models.CharField(max_length=500),
        ),
    ]
