# Generated by Django 4.1.6 on 2023-02-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quoteapp", "0006_alter_quote_quote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="quote",
            field=models.CharField(max_length=200),
        ),
    ]
